name: GitHub Actions Test
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      uses: actions/setup-node@v3

    - name: Test
      run: npm install && npm run test