name: GitHub Actions Test
on:
  push:
    branches:
      - master
    paths:
      - './backend/**'
      - './frontend/**'
  pull_request:
    branches:
      - master
    paths:
      - './backend/**'
      - './frontend/**'
jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v3

    - name: Install dependencies & Test
      run: npm install && npm run test

  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v3

    - name: Install dependencies & Test
      run: npm install && npm run test